version: "3"
services:
    prod:
        image: erru17/microblog:v1.0.1-prod
        container_name: microblog-production
        ports:
            - "8000:5000"
        environment:
          DATABASE_URL: "mysql+pymysql://microblog:${DB_PASSWORD}@dbserver/microblog"
        depends_on:
          - db

    db:
      image: mysql/mysql-server:5.7
      container_name: dbserver
      volumes:
        - ./db:/var/lib/mysql
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        MYSQL_DATABASE: "microblog"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
