FROM python:3.8-alpine3.16

WORKDIR /home/microblog
RUN adduser -D microblog
ENV FLASK_APP microblog.py

COPY requirements.txt microblog.py boot.sh ./
COPY requirements requirements
COPY migrations migrations
COPY gunicorn_config.py gunicorn_config.py

RUN python -m venv venv && \
    venv/bin/pip3 install -r requirements.txt && \
    chown -R microblog:microblog ./

COPY app app

RUN chown -R microblog:microblog app migrations && \
    chmod +x boot.sh

USER microblog

ENV prometheus_multiproc_dir /tmp

EXPOSE 5000

ENTRYPOINT ["./boot.sh"]