FROM python:3.8-alpine3.16

WORKDIR /home/microblog
RUN adduser -D microblog && \
    apk add --no-cache make=4.3-r0

COPY requirements requirements
COPY boot_test.sh Makefile .coveragerc .pylintrc  pytest.ini ./

RUN python -m venv venv && \
    venv/bin/pip3 install -r requirements/test.txt && \
    chown -R microblog:microblog ./ && \
    chmod +x boot_test.sh

User microblog

ENTRYPOINT ["./boot_test.sh"]