---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: aHVuZA==
  DB_PASSWORD: bWljcm9ibG9n
  DB_URL: bXlzcWwrcHlteXNxbDovL21pY3JvYmxvZzptaWNyb2Jsb2dAbXlzcWw6MzMwNi9taWNyb2Jsb2c=
