name: Publish to Docker

on:
  workflow_run:
    workflows: ["Test and Validate"]

jobs:
  test-and-validate:
    uses: ./.github/workflows/tests.yml

  push_to_docker:
    needs: test-and-validate
    name: Push Docker image to Docker Hug
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile_prod
          push: true
          tags: erru17/microblog:latest
