name: Check Docker using Snyk 
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  publish-image:
    uses: ./.github/workflows/publish_docker.yml
  security:
    needs: publish-image
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: erru17/microblog:latest
